
package dasniko.keycloak.authenticator.ma.gbp.digital.smsgateway.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "SmsCanaryServiceService", targetNamespace = "http://service.SmsGateway.digital.gbp.ma/", wsdlLocation = "http://10.3.110.37/services/sms?wsdl")
public class SmsCanaryServiceService
    extends Service
{

    private final static URL SMSCANARYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SMSCANARYSERVICESERVICE_EXCEPTION;
    private final static QName SMSCANARYSERVICESERVICE_QNAME = new QName("http://service.SmsGateway.digital.gbp.ma/", "SmsCanaryServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.3.110.37/services/sms?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMSCANARYSERVICESERVICE_WSDL_LOCATION = url;
        SMSCANARYSERVICESERVICE_EXCEPTION = e;
    }

    public SmsCanaryServiceService() {
        super(__getWsdlLocation(), SMSCANARYSERVICESERVICE_QNAME);
    }

    public SmsCanaryServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMSCANARYSERVICESERVICE_QNAME, features);
    }

    public SmsCanaryServiceService(URL wsdlLocation) {
        super(wsdlLocation, SMSCANARYSERVICESERVICE_QNAME);
    }

    public SmsCanaryServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMSCANARYSERVICESERVICE_QNAME, features);
    }

    public SmsCanaryServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmsCanaryServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SoapdemoWsdlPortType
     */
    @WebEndpoint(name = "SmsCanaryServicePort")
    public SoapdemoWsdlPortType getSmsCanaryServicePort() {
        return super.getPort(new QName("http://service.SmsGateway.digital.gbp.ma/", "SmsCanaryServicePort"), SoapdemoWsdlPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapdemoWsdlPortType
     */
    @WebEndpoint(name = "SmsCanaryServicePort")
    public SoapdemoWsdlPortType getSmsCanaryServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.SmsGateway.digital.gbp.ma/", "SmsCanaryServicePort"), SoapdemoWsdlPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMSCANARYSERVICESERVICE_EXCEPTION!= null) {
            throw SMSCANARYSERVICESERVICE_EXCEPTION;
        }
        return SMSCANARYSERVICESERVICE_WSDL_LOCATION;
    }

}
